### ISSUE TITLE
How about XmlDocument.Load()?

### ISSUE THREAD

**Issue by sturlath** [WrapThat/WrapThat.System#1]
I need to be able to mock out the Load() part from disk (filename).

Would you take a PR for that? I really need that one. Would it be implemented like everything else here or do you have any preference?

**Comment by OsirisTerje** [comment]
Makes sense, and yes, absolutely takes PRs.  And if you use the generator in there around XmlDocument you should get both the Load and other static methods. 
But feel free to do that or just in whatever way you're comfortable with.   I can update with the rest later also. 

Update:
Just checked the XmlDocument class, and the Load method is not static, means it is not suitable for the way WrapThat does this.   Did you mean the XDocument class Load methods, because they are static and thus suitable.

**Comment by sturlath** [comment]
Ok I had not looked at in details how WrapThat worked. It only works for static methods?

But I had planned on changing my xml implementation from using XmlDocument to XDocument  so this will just force me to do that. 

So I would implement the following

```
public static XDocument Load(string uri);
public static XDocument Load(string uri, LoadOptions options);
public static XDocument Load(XmlReader reader);
public static XDocument Load(XmlReader reader, LoadOptions options);
public static XDocument Load(TextReader textReader);
public static XDocument Load(Stream stream);
public static XDocument Load(Stream stream, LoadOptions options);
public static XDocument Load(TextReader textReader, LoadOptions options);
public static XDocument Parse(string text);
public static XDocument Parse(string text, LoadOptions options);
```

But how would I mock the none static Save() method? 

``` 
public void Save(string fileName); 
```

**Comment by OsirisTerje** [comment]
Yes, the lib "as is" only works on static methods. 
About the Save:  You can't mock it directly like the static methods, so you would have to make a wrapper for XDocument with an interface you can mock.  That would also mean you would need the static methods to return that interface instead. 
This is the reason I didn't include the instance methods in the lib, it just starts to become more complicated, and there are different ways, and opinions on how to go about that.  
I would wrap the whole xml loading and saving in an adapter class, with an interface to be mocked.  
If you create an adapter with the absolute minimal of code, you skip the testing on that one, and use the adapter instead as the testing "interface" border.

**Comment by OsirisTerje** [comment]
@sturlath Long time, but did you do anything about XDocument Load?

**Comment by sturlath** [comment]
Yes long time indeed but I cant remember what I did (left that company) but I must likely did what you you suggested, wrapped it.
